START_TIME = '23:55'
FORMAT_DATE = '%Y-%m-%d'
FORMAT_DATETIME = '%Y-%m-%d %H:%M:%S'

MAX_DELAY = 300

RABBITMQ_EXCHANGE_NAME = 'social_listening'
RABBITMQ_EXCHANGE_TYPE = 'direct'
RABBITMQ_TASK_QUEUE = 'task_queue'
RABBITMQ_MONITOR_QUEUE = 'monitor_queue'
RABBITMQ_RISK_QUEUE = 'risk_queue'
RABBITMQ_QUEUE_DURABLE = True
RABBITMQ_DELIVERY_MODE = 2

# MQTT topic
MQTT_TOPIC_TASK = 'task'
MQTT_TOPIC_EMERGENCY_ACCOUNT = 'emergency/account'
MQTT_TOPIC_EMERGENCY_FOLLOWING = 'emergency/following'
MQTT_TOPIC_JOB_UPDATE = 'job/update'

# Status for account
STATUS_ACCOUNT_NOT_ACTIVATED = 0
STATUS_ACCOUNT_ACTIVATED = 1
STATUS_ACCOUNT_ERROR_NOT_REPLACED = 2
STATUS_ACCOUNT_ERROR_REPLACED = 3
STATUS_ACCOUNT_BACKUP = 10

# Status for following
STATUS_FOLLOWING_NOT_ACTIVATED = 0
STATUS_FOLLOWING_ACTIVATED = 1
STATUS_FOLLOWING_ERROR = 2

# Status for server
STATUS_SERVER_NOT_ACTIVATED = 0
STATUS_SERVER_ACTIVATED = 1

# Status for cluster
STATUS_CLUSTER_NOT_ACTIVATED = 0
STATUS_CLUSTER_ACTIVATED = 1

# Status for JOB
JOB_STATUS_SEND_SUCCESSFULLY = 0
JOB_STATUS_STARTED_SUCCESSFULLY = 1
JOB_STATUS_STARTED_FAILED = 2

# Error code for JOB
JOB_ERROR_CODE_ACCOUNT_ERROR = 801
JOB_ERROR_CODE_EXCEED_VALID_EXECUTED_AT = 802